{
 "title": "CPU Consumption",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Percentage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "sreagent_cpu_percent" }
   ]
  },
  {
   "title": "CPU consumption in MHz",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sreagent_cpu_mhz" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sreagent_mem_metrics{use=\"utilization\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sreagent_load_metrics{use=\"load1m\"}",
     "legendFormat": "Load1m"
    },
    {
     "expr": "sreagent_load_metrics{use=\"load5m\"}",
     "legendFormat": "Load5m"
    }
   ]
  }
 ]
}