{
 "title": "Details for FS and Net",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Filesystem Use (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sreagent_fs{metric=\"usedpercent\"}"
    }
   ]
  },
  {
   "title": "Filesystem Free Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sreagent_fs{metric=\"freespaceGB\"}"
    }
   ]
  },
  {
   "title": "Net Data",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sreagent_net{net=\"eth0\"}"
    }
   ]
  }
 ]
}