{
 "title": "Net and Disk Operations",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Connection Metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sreagent_conn_metrics" }
   ]
  },
  {
   "title": "IP Packets per Second",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sreagent_net_rates{unit=\"pps\"}"
    }
   ]
  },
  {
   "title": "IP Mbits per Second",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "sreagent_net_rates{unit=\"mbps\"}"
    }
   ]
  },
  {
   "title": "Disk IO per Second",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sreagent_disk_rates{unit=\"iops\"}"
    }
   ]
  },
  {
   "title": "Disk MB per Second",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "sreagent_disk_rates{unit=\"mbps\"}"
    }
   ]
  }
 ]
}