{
 "title": "SRE Agent Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Overhead",
   "type": "singlestat",
   "description": "Overhead to get the associated metrics",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_cpu\",instance=\"ubuntu-agent:9000\"}"
    }
   ]
  },
  {
   "title": "CPU Overhead",
   "type": "singlestat",
   "description": "Overhead to get the associated metrics",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_cpu\",instance=\"alpine-agent:9000\"}"
    }
   ]
  },
  {
   "title": "MEM Overhead",
   "type": "singlestat",
   "description": "Overhead to get the associated metrics",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_mem\",instance=\"ubuntu-agent:9000\"}"
    }
   ]
  },
  {
   "title": "OS LOAD Overhead",
   "type": "singlestat",
   "description": "Overhead to get the associated metrics",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_load\",instance=\"ubuntu-agent:9000\"}"
    }
   ]
  },
  {
   "title": "Heatmap of Measuring Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_cpu\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_mem\"}",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "Plugin Measure Overhead",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_cpu\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "agent_plugin_overhead_ms{plugin=\"plugin_mem\"}",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "Agent Ticks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "agent_plugin_ticks" }
   ]
  },
  {
   "title": "Agent Plugin Bytes Monitored",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "agent_bytes_sent" }
   ]
  }
 ]
}