version: "3"
services:
  ubuntu-agent:
    image:              ubuntu:18.04
    container_name:     ubuntu-agent
    hostname:           ubuntu-agent
    command:            /bin/bash -c "cd /sreagent && sre-agent/Linux/sre-agent -d -f sre-agent/config/agent.Linux.yaml "
    ports:
      - 9000:9000
    volumes:
      - $GOPATH/src/github.com/gus-maurizio/:/sreagent
#
  alpine-agent:
    image:              alpine:latest
    container_name:     alpine-agent
    hostname:           alpine-agent
    command:            /bin/sh -c "cd /sreagent && sre-agent/Alpine/sre-agent -d -f sre-agent/config/agent.Linux.yaml "
    ports:
      - 9010:9000
    volumes:
      - $GOPATH/src/github.com/gus-maurizio/:/sreagent
#
  prometheus:
    image:              prom/prometheus
    container_name:     prom
    hostname:           prom
    command:            --config.file=/etc/prometheus.docker.yaml
    ports:
      - 9090:9090
    volumes:
      - $GOPATH/src/github.com/gus-maurizio/sre-agent/Prometheus-Config/prometheus.docker.yaml:/etc/prometheus.docker.yaml
      - promdata:/prometheus
#
  grafana:
    image:              grafana/grafana
    container_name:     grafana
    hostname:           grafana
    ports:
      - 3000:3000
    volumes:
      - grafdata:/var/lib/grafana
#
  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  #   container_name: es
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - esdata1:/usr/share/elasticsearch/data
  # web:
  #   image: prakhar1989/foodtrucks-web
  #   command: python app.py
  #   depends_on:
  #     - es
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./flask-app:/opt/flask-app
volumes:
    promdata:
      driver: local
    grafdata:
      driver: local