# config of runtime
applicationid:          ASVMYNAME
moduleid:               go.agent
versionid:              1.0.0.a
environmentid:          Production
#------------------------------------------------------------------------------#
# log preferences
logformat:		JSON
#logdest:		STDERR
prettyprint:		true
disabletimestamp:	false
#------------------------------------------------------------------------------#
# Prometheus metric expose
prometheusport:		9000
metrichandle:		/metrics
healthhandle:		/health
detailhandle:		/detail/
#------------------------------------------------------------------------------#
# defaults for Plugins 
defaulttimetick:        500ms
defaultmeasuredest:	["file","/tmp/sre-agent.measure.log"]
defaultalertdest:	["file","/tmp/sre-agent.alert.log"]
defaultwarndest:	["file","/tmp/sre-agent.warn.log"]
#--- two rolling windows are kept to calculate error and warning densities
defaultrollingwindow1:	15m
defaultrollingwindow2:	1h
#--- error and warning default thresholds
#---   the idea is that errors and warnings can be ephemeral
#---   and we need to get a few # in each window to call it an emegency
#---   we also want to limit the # of alerts sent!
#---   example:
#---      # of ticks in Roll W1: 15m/500ms = 1800
#---      # of ticks in Roll W2: 1h/500ms  = 7200
#---      when 03 errors   are detected in 1800 ticks, an ALERT    will be sent
#---      when 40 warnings are detected in 1800 ticks, a  WARNINGn will be sent
#---      same concept applies to Rolling Window 2
defaulterrorthresh1: 	3
defaultwarnthresh1:  	40
#
defaulterrorthresh2:    10
defaultwarnthresh2:    40
#
#------------------------------------------------------------------------------#
# plugin configuration section
plugins:
  - pluginname:			plugin_system
    measuredest:		["udp",":4321"]
    alertdest:			["udp",":4322"]
    warndest:			["udp",":4323"]
    pluginmodule:		./darwin/amd64/plugins/plugin_system.so
    plugintimetick:		10s
    pluginconfig:		'{ "alert_blue": "5%", "alert_green": "70%" }'
    pluginrollingwindow1:	1m
    pluginrollingwindow2:	5m
    pluginerrorthresh1:    	3
    pluginwarnthresh1:     	40
    #
    pluginerrorthresh2:    	10
    pluginwarnthresh2:    	40
#
  - pluginname:         plugin_network
    measuredest:	["file","/tmp/sre-agent.plugin_network.measure.log"]
    pluginmodule:       ./darwin/amd64/plugins/plugin_network.so
    plugintimetick:     2s
    pluginconfig:       '
{ "alert": {    "blue":   [0,  3], 
		"green":  [3,  60],
		"yellow": [60, 80],
		"orange": [80, 90],
		"red":    [90, 100]
	   } 
}
'
#
#------------------------------------------------------------------------------#
#
