global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'sre-agent'
    metrics_path: /metrics
    scrape_interval: 1s
    scrape_timeout:  1s
    scheme: http
    static_configs:
      - targets: 
        - ubuntu-agent:9000
        - alpine-agent:9000
#        - docker.for.mac.host.internal:9000
#        - docker.for.mac.host.internal:9010
